# Generated by Django 3.2.12 on 2022-04-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Admin',
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True)),
                ('github', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_offers', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(default='dypatil@123', max_length=50)),
                ('photo', models.ImageField(blank=True, default=None, upload_to='studentPhoto')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('rait_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Student',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_one', models.ImageField(blank=True, default=None, upload_to='certificate')),
                ('certificate_two', models.ImageField(blank=True, default=None, upload_to='certificate')),
                ('certificate_three', models.ImageField(blank=True, default=None, upload_to='certificate')),
                ('certificate_four', models.ImageField(blank=True, default=None, upload_to='certificate')),
                ('acad_achievement_one', models.CharField(blank=True, max_length=50, null=True)),
                ('acad_achievement_two', models.CharField(blank=True, max_length=50, null=True)),
                ('acad_achievement_three', models.CharField(blank=True, max_length=50, null=True)),
                ('acad_achievement_four', models.CharField(blank=True, max_length=50, null=True)),
                ('career_obj', models.CharField(blank=True, max_length=1000, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpc_api.student')),
            ],
            options={
                'verbose_name_plural': 'Student SkillSet',
                'db_table': 'student_skillset',
            },
        ),
        migrations.CreateModel(
            name='PlacementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_letter_one', models.ImageField(blank=True, default=None, upload_to='offerLetter')),
                ('offer_letter_two', models.ImageField(blank=True, default=None, upload_to='offerLetter')),
                ('placed_org_one', models.CharField(blank=True, max_length=50, null=True)),
                ('placed_org_two', models.CharField(blank=True, max_length=50, null=True)),
                ('package_one', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('package_two', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpc_api.student')),
            ],
            options={
                'verbose_name_plural': 'Student Placement Detail',
                'db_table': 'student_placement_details',
            },
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(blank=True, max_length=1000, null=True)),
                ('pos_of_res_one', models.CharField(blank=True, max_length=50, null=True)),
                ('pos_of_res_two', models.CharField(blank=True, max_length=50, null=True)),
                ('pos_of_res_three', models.CharField(blank=True, max_length=50, null=True)),
                ('pos_of_res_four', models.CharField(blank=True, max_length=50, null=True)),
                ('extracuricular_one', models.CharField(blank=True, max_length=500, null=True)),
                ('extracuricular_two', models.CharField(blank=True, max_length=500, null=True)),
                ('extracuricular_three', models.CharField(blank=True, max_length=500, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpc_api.student')),
            ],
            options={
                'verbose_name_plural': 'Student Other Info',
                'db_table': 'other_info',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('internship_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('internship_three', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_three', models.CharField(blank=True, max_length=1000, null=True)),
                ('pref_lang', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies', models.CharField(blank=True, max_length=1000, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpc_api.student')),
            ],
            options={
                'verbose_name_plural': 'Student Experience',
                'db_table': 'student_experience',
            },
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('twelveth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sem1_pointer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sem2_pointer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sem3_pointer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sem4_pointer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sem5_pointer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sem6_pointer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sem7_pointer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sem8_pointer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('be_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpc_api.student')),
            ],
            options={
                'verbose_name_plural': 'Student Academic Info',
                'db_table': 'academic_info',
            },
        ),
    ]
