# Generated by Django 3.2.13 on 2022-06-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('tpc_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligiblestudents',
            name='job_opening',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='company.jobopening'),
        ),
    ]
