# Generated by Django 3.2.12 on 2022-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinfo',
            name='diploma_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='diploma_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='diploma_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='diploma_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem1_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem1_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem1_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem1_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem2_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem2_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem2_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem2_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem3_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem3_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem3_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem3_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem4_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem4_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem4_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='masters_sem4_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem1_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem1_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem1_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem2_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem2_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem2_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem3_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem3_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem3_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem4_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem4_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem4_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem5_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem5_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem5_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem6_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem6_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem6_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem7_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem7_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem7_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem8_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem8_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='sem8_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='tenth_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='tenth_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='tenth_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='twelveth_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='twelveth_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='twelveth_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
