# Generated by Django 3.2.13 on 2022-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0002_alter_eligiblestudents_job_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='be_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='deadkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='diploma_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='diploma_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='diploma_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='diploma_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='gap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='livekt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem1_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem1_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem1_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem1_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem2_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem2_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem2_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem2_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem3_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem3_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem3_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem3_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem4_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem4_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem4_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='masters_sem4_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem1_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem1_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem1_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem1_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem2_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem2_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem2_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem2_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem3_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem3_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem3_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem3_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem4_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem4_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem4_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem4_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem5_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem5_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem5_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem5_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem6_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem6_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem6_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem6_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem7_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem7_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem7_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem7_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem8_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem8_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem8_pointer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='sem8_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='tenth_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='tenth_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='tenth_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='tenth_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='twelveth_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='twelveth_obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='twelveth_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='twelveth_total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='internship_one',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='internship_three',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='internship_two',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='pref_lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='project_one',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='project_three',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='project_two',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='technologies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='extracuricular_one',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='extracuricular_three',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='extracuricular_two',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='hobbies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='pos_of_res_four',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='pos_of_res_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='pos_of_res_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='pos_of_res_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='offer_letter_one',
            field=models.ImageField(blank=True, default=None, upload_to='offerLetter'),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='offer_letter_two',
            field=models.ImageField(blank=True, default=None, upload_to='offerLetter'),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='package_one',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='package_two',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='placed_org_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='placed_org_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='acad_achievement_four',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='acad_achievement_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='acad_achievement_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='acad_achievement_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='career_obj',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='certificate_four',
            field=models.ImageField(blank=True, default=None, upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='certificate_one',
            field=models.ImageField(blank=True, default=None, upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='certificate_three',
            field=models.ImageField(blank=True, default=None, upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='certificate_two',
            field=models.ImageField(blank=True, default=None, upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='no_of_offers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='studentPhoto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rait_email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
