# Generated by Django 3.2.13 on 2022-06-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0003_auto_20220606_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdetails',
            name='offer_letter_three',
            field=models.ImageField(blank=True, default=None, upload_to='offerLetter'),
        ),
        migrations.AddField(
            model_name='placementdetails',
            name='package_three',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='placementdetails',
            name='placed_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placementdetails',
            name='placed_org_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placementdetails',
            name='placed_package',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
