# Generated by Django 3.2.12 on 2022-06-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdetails',
            name='package_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='package_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='package_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
