# Generated by Django 3.2.12 on 2022-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0004_auto_20220623_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdetails',
            name='placed_package',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
