# Generated by Django 3.2.13 on 2022-06-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0004_auto_20220606_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='acad_achievement_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='acad_achievement_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='acad_achievement_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='acad_achievement_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='certificate_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='certificate_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='certificate_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='certificate_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
