# Generated by Django 3.2.12 on 2022-05-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0005_auto_20220503_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
