# Generated by Django 3.2.13 on 2022-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0006_auto_20220607_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='internship_one',
            new_name='internship_one_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='internship_three',
            new_name='internship_three_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='internship_two',
            new_name='internship_two_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='project_one',
            new_name='project_one_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='project_three',
            new_name='project_three_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='project_two',
            new_name='project_two_description',
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_one_end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_one_start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_one_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_three_end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_three_start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_three_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_two_end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_two_start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='internship_two_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_one_end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_one_start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_one_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_three_end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_three_start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_three_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_two_end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_two_start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project_two_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skillset',
            name='certificate_four_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skillset',
            name='certificate_one_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skillset',
            name='certificate_three_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skillset',
            name='certificate_two_completion_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
