# Generated by Django 3.2.13 on 2022-06-04 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('tpc_api', '0006_remove_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinfo',
            name='deadkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='gap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='livekt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EligibleStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobopening')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eligible Students',
                'db_table': 'eligible_students',
            },
        ),
    ]
