# Generated by Django 3.2.13 on 2022-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0007_auto_20220611_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdetails',
            name='offer_letter_one',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='offer_letter_three',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementdetails',
            name='offer_letter_two',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
