# Generated by Django 4.0.5 on 2022-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpc_api', '0008_auto_20220616_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EligibleStudents',
        ),
    ]
