# Generated by Django 4.0.5 on 2022-06-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_initial'),
        ('tpc_api', '0009_alter_student_photo_delete_eligiblestudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_opening', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='company.jobopening')),
                ('student', models.ForeignKey(db_column='roll_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eligible Students',
                'db_table': 'eligible_students',
            },
        ),
    ]
