# Generated by Django 3.2.13 on 2022-06-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('valid_till', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('offers', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('twelveth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diploma_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('be_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('live_kt', models.CharField(blank=True, max_length=50, null=True)),
                ('dead_kt', models.CharField(blank=True, max_length=50, null=True)),
                ('notice', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Job Openings',
                'db_table': 'job_openings',
            },
        ),
    ]
