# Generated by Django 3.2.13 on 2022-06-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='gap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='package',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='dead_kt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='live_kt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
