# Generated by Django 4.0.5 on 2022-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_delete_jobopening'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('valid_till', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('offers', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('twelveth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diploma_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('be_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notice', models.TextField(blank=True, null=True)),
                ('live_kt', models.IntegerField(blank=True, null=True)),
                ('dead_kt', models.IntegerField(blank=True, null=True)),
                ('gap', models.IntegerField(blank=True, null=True)),
                ('package', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Job Openings',
                'db_table': 'job_openings',
            },
        ),
    ]
